"""Classes to define Restaurant Info

Hierachy of Classes:
- Restaurant Info: Object
    - Unique Id: UUID
    - Restaurant Name: str
    - Location: Object
        - Coordinate: Object
        - Address: Object
    - OpeningHours: Object
    - Food Categories: Optional[Set[str]]
    - MenuURL: Optional[HttpUrl]
    - Services: List[str]                  # TODO: Figure out generate
    - Safety Measures: List[str]
    - Dining Ameneties: List[str]
    - Delivery Services: Object
    - Inclusive Tags: List[str]
    - Wheelchair Accessibity: List[str]
"""

from typing import Optional, Set
from uuid import UUID, uuid4

from pydantic import BaseModel, Field, constr, HttpUrl

from .utils    import to_lower_camel
from .location import Coordinate
from .services import Services


class Restaurant(BaseModel):
    """Class for full restaurant info with validation

    Attributes:
        id (UUID): Unique UUID generated by default
        name (str): Restaurant Name
        location (Location):
            Data containing coordinate + address
        opening_hours (OpeningHours):
            A list of hours in the week for available services
        food_category (Set[FoodCategory]):
            A set of type of food, should be non-empty
        services (Services):
            A list of pickup and deliver services available
    """
    id: UUID = Field(default_factory=uuid4)
    name: str
    coordinate: Coordinate
    address: Optional[constr(min_length=1)]
    food_categories: Set[str] = set()
    menu_url: Optional[HttpUrl]
    services: Services = Services()

    class Config:
        """Config for Restaurant Model

        - Must comply as typical JS/JSON variable name
        """
        alias_generator = to_lower_camel
